// Master mod registry. SOURCE OF TRUTH for mod gallery + mods index + related sections.
// `real: true` means the mod exists on moddable.games. `real: false` is invented copy.

window.MODS = [
  { slug: "talisman-hexed",  real: true,
    category: "Reskin", baseGame: "Talisman 4e",
    title: "Talisman: Hexed",
    body: "Replaces the Talisman boards with 61 hexagonal tiles arranged in concentric rings. Open-world hex system — every game lays out differently.",
    stats: "2–6 players · 90 min · 13+",
    href: "../mod-detail/index.html",
  },
  { slug: "econopoly", real: true,
    category: "Total conversion", baseGame: "Monopoly",
    title: "Econopoly",
    body: "Monopoly converted into a family-friendly Euro-game. Resource management, victory points, no bankruptcy-fuelled estrangements at Christmas.",
    stats: "2–4 players · 60 min · 10+",
    href: "../mods/econopoly.html",
  },
  { slug: "hyper-imperium", real: true,
    category: "Rebalance", baseGame: "Twilight Imperium 4e",
    title: "Hyper Imperium",
    body: "Hyper Movement · Hyper Trades · Hyper Objectives · Hyper Factions · Hyper Agendas. A faster ruleset for TI4 that keeps the politics intact.",
    stats: "3–6 players · 4–6 hr · 14+",
    href: "../mods/hyper-imperium.html",
  },
  // ----- invented below; clearly flagged -----
  { slug: "nuke-catan", real: false,
    category: "Total conversion", baseGame: "Catan",
    title: "Are you ready to <em>nuke</em> Catan?",
    body: "A post-apocalyptic rules overhaul. Sheep are scarce, brick is currency, and someone is going to set fire to the road network.",
    stats: "3–5 players · 60 min · 12+",
    href: "../mods/nuke-catan.html",
  },
  { slug: "chess-constraints", real: false,
    category: "Total conversion", baseGame: "Chess",
    title: "Conquering the constraints of chess",
    body: "An 11×11 board, three new pieces, fog-of-war. Plays like chess if chess were designed by Borges.",
    stats: "2 players · 30 min · 10+",
    href: "../mods/chess-constraints.html",
  },
  { slug: "beyond-the-box", real: false,
    category: "Reskin", baseGame: "Risk",
    title: "Beyond the box",
    body: "Risk on a Martian colony grid. Same rules, new theme, plus a single rule for orbital strikes.",
    stats: "2–6 players · 120 min · 12+",
    href: "../mods/beyond-the-box.html",
  },
  { slug: "cattle-drives", real: false,
    category: "Rebalance", baseGame: "Catan",
    title: "Cattle drives",
    body: "Adds a herd-movement phase between standard turns. Sheep gain agency.",
    stats: "3–4 players · 75 min · 10+",
    href: "../mods/cattle-drives.html",
  },
  { slug: "lunar-colony", real: false,
    category: "Reskin", baseGame: "Catan",
    title: "Catan: lunar colony",
    body: "Same rules, new theme. The robber is now an oxygen leak.",
    stats: "3–4 players · 60 min · 10+",
    href: "../mods/lunar-colony.html",
  },
  { slug: "cataclysm", real: false,
    category: "Total conversion", baseGame: "Catan",
    title: "Cataclysm",
    body: "Every turn the board loses a hex. Race to hit 8 VP before the island sinks.",
    stats: "3–4 players · 50 min · 12+",
    href: "../mods/cataclysm.html",
  },
];

window.GAMES = [
  { slug: "endless-skies", real: false /* original game — design's invented */,
    title: "Endless Skies",
    body: "A hex-tile exploration game built to be modded. Three biomes, twelve faction decks, one rulebook with version control.",
    stats: "2–4 players · 60–90 min · 12+",
    href: "../game-detail/index.html",
    color: "#0c4f8d",
  },
  { slug: "mongo", real: false,
    title: "Mongo",
    body: "A trick-taking card game for tabletop modders. Open playtest, 200 spots.",
    stats: "3–5 players · 30 min · 12+",
    href: "../games/mongo.html",
    color: "#3a9928",
  },
  { slug: "nukes", real: false,
    title: "Nukes",
    body: "Cold war on a hex map. Three superpowers, fifteen turns, one button.",
    stats: "2–4 players · 45 min · 14+",
    href: "../games/nukes.html",
    color: "#d11a1a",
  },
];
